### ISSUE TITLE
hexo g 报错 TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by xuesongzh** [sunchaser-lilu/hexo-theme-book#1]
hexo g -d
INFO  Validating config
(node:32297) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
**TypeError: Cannot read properties of undefined (reading 'path')**
    at Hexo.<anonymous> (/Users/zxsong/Downloads/ubuntu/blog/themes/book/scripts/render.js:52:31)
    at Hexo.tryCatcher (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/zxsong/Downloads/ubuntu/blog/node_modules/hexo/dist/extend/filter.js:58:67
    at tryCatcher (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/zxsong/Downloads/ubuntu/blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by llnancy** [comment]
you can refer to https://hexo.io/docs/troubleshooting.html#Template-render-error
